name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          # this line is required for the setup-node action to be able to run the npm publish below.
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      # install playwright after linting, so that we have a faster linting process
      - name: Install playwright browsers
        run: npx playwright install --with-deps
      - run: yarn test --all
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          verbose: true
      - run: yarn manifest
      - run: yarn build
      - run: npm run publish-release -- canary
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
